alias push='git push'
alias pull='git pull'
alias add='git add -A'
alias branch='git branch'
alias switch='git checkout'
alias status='git status'
alias scommit='git commit -m'
alias commit='git commit'
alias clone='git clone'
alias log='git log --graph --decorate --pretty=oneline --abbrev-commit'
alias merge='git merge'
alias gdiff='git diff'
alias p='python3'
alias dotman='$HOME/dotman/dotman.sh'
alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
alias z=zsh
alias b=bash
