#!/usr/bin/env bash

# FZF Wrapper over github CLI to interactively view diff on PRs


# 1. Get local file path from the user
# 2. Find all open PRs
# 3. For files changed in each PR find PR which changes the user provided file path
# 4. Output the PR (id, url) and its diff


# TODO: handle how to print diff

git_file=$(git ls-files | fzf \
  --prompt="Choose File: " \
  --height 40% --reverse \
  --header="Choose a file to find pull requests that change this file"
)

all_open_prs=$(gh pr list --json number,title,url,files)
total_prs=$(echo "$all_open_prs" | jq length)

printf "%s\n\n" "Hold tight while we look for PRs ✋👀 that modify $(tput bold)$git_file$(tput sgr0)"
for (( c=0; c<total_prs; c++ )); do
    pr_number=$(echo "$all_open_prs" | jq .["$c"].number)
    readarray -t changed_files < <(echo "$all_open_prs" | jq .["$c"].files[].path | tr -d '"')
    if [[ " ${changed_files[*]} " =~ " ${git_file} " ]]; then
        echo "Found PR #$pr_number which changes the file path $(tput bold)$git_file$(tput sgr0)"
        echo -e "Title: $(tput bold)$(echo "$all_open_prs" | jq .["$c"].title | tr -d '"')$(tput sgr0)"
        echo -e "URL: $(tput setaf 69)$(tput bold)$(echo "$all_open_prs" | jq .["$c"].url | tr -d '"')$(tput sgr0)\n"
        #echo "Showing diff for the PR $pr_number"
        #gh pr diff "$pr_number"
    fi
done
