#!/usr/bin/env bash

# FZF Wrapper over git to interactively work with git worktrees
# Automate your git worktrees create & switch lifecycle

# Dependencies:
# 1. FZF
# 2. Bash>=4
# 3. Basic Utils: AWK, dirname, basename, grep, column, comm

# READ BEFORE USE
#
# This script assumes the following git worktree flow
#
# SOME_DIRECTORY
# │
# ├────beepbop (main git repository or main worktree)
# │    │
# │    ├────.git (dir)
# │    │
# │    └────README.md
# │
# └────beepbop-worktrees (all linked worktrees)
#      │
#      ├────a1 (linked worktree)
#      │    │
#      │    ├────.git (file)
#      │    │
#      │    └────README.md
#      └────a2 (linked worktree)
#           │
#           ├────.git (file)
#           │
#           └────README.md

# Installation & Usage:
#
# $ curl -s https://raw.githubusercontent.com/Bhupesh-V/.Varshney/master/scripts/git/git-worktree-all -o giw
#
# $ source giw
# 
# TODO: set $GIT_WORK_TREE env variable
# TODO: set config for core.worktree
# TODO: highlight the main worktree branch?

RESET=$(tput sgr0)
BOLD=$(tput bold)

create_worktree() {
    # avoid nesting of worktrees by switching to main worktree 😅
    switch_to_main_tree

    # TODO check if main worktree is in sync with remote
    common_dir=$(dirname "$(pwd)")
    git_main_dir=$(basename "$(pwd)")
    new_worktree="$common_dir/$git_main_dir-worktrees/$1"

    source_branch=$(git for-each-ref --format='%(refname:short)' refs/heads | fzf\
        --prompt="Choose a source branch for $1: " \
        --height 40% --reverse --ansi\
        --header="Create a worktree from pre-existing branch. (Ctrl+C to use main)" | awk '{print $1}'
    )

    if [[ -z $source_branch ]]; then
        git worktree add "$new_worktree"
    else
        # create worktree from custom branch
        if git branch "$1" "$source_branch"; then
            git worktree add "$new_worktree" "$1"
        fi
    fi

    find_copy_gitignored_paths "$new_worktree"

    printf "%s\n" "Switching to worktree, $BOLD$1${RESET}"
    switch_worktree "$1"
}

switch_worktree() {
    # switch current worktree in the terminal
    worktree=$(git worktree list | grep -m 1 -w "$1" | awk '{print $1}')

    cd "$worktree" || printf "%s\n" "Can't find the linked worktree" && return
}

switch_to_main_tree() {
    if file .git | grep -w "ASCII text" 1> /dev/null; then
        printf "%s" "Switching to main worktree: "
        linked_tree_path=$(cat .git | awk '{print $2}')
        # gitdir: SOME_PATH/.git/worktrees/PWD
        current_linked_tree=$(basename "$(pwd)")
        main_worktree_path=${linked_tree_path%.git/worktrees/$current_linked_tree}
        printf "%s\n" "$BOLD$main_worktree_path$RESET"

        cd "$main_worktree_path" || return

        # verify if we are in main worktree
        if file .git | grep -w ".git: directory" 1> /dev/null; then
            return
        else
            printf "%s\n" "Failed to switch to main worktree"
            exit 1
        fi
    fi
}

# copy any gitignored paths to a worktree
# Good for copying paths like .vscode/, .env
find_copy_gitignored_paths() {

    # Get all the files which are tracked
    tracked_files=$(git ls-tree --name-only $(git branch --show-current) > /tmp/tracked_files)
    # Get list of all files in repository, hidden or not
    all_filepaths=$(find . -mindepth 1 -maxdepth 1 -mtime -14 -not -path "./.git" -printf '%f\n' > /tmp/all_files)
    # Difference b/w these 2 lists
    difference=$(comm -23 <(sort /tmp/all_files) <(sort /tmp/tracked_files))

    [[ -z $difference ]] && return

    # Ask the user what they want to copy
    readarray -t choice_paths_to_copy < <(printf "%s" "$difference" | fzf \
        --prompt="Choose filepaths to copy (TAB to select): " \
        --height 40% --reverse --multi \
        --header="These files are ignored by git while creating a worktree (Ctrl+C to skip)"
    )

    [[ -z $choice_paths_to_copy ]] && return

    # Copy the choosen files
    for ignored_file in "${choice_paths_to_copy[@]}"
    do
        if cp -r "$ignored_file" "$new_worktree"; then
            printf "%s\n" "Copied $BOLD$ignored_file$RESET to worktree"
        fi
    done

}

init_worktree_menu() {
    # list available branches that have a worktree associated with them
    # in any case the default tree with "main" branch is printed

    worktree=$(
        git for-each-ref --color=always \
        --format='%(if)%(worktreepath)%(then)%(color:bold)%(refname:short)%(color:reset) [%(color: bold 154)%(objectname:short)%(color:reset)] %(color:bold 208)%(align:63,left)%(worktreepath)%(end)%(color:reset) %(end)' |\
        column -t | fzf \
        --prompt="Choose a Worktree or Create One: " \
        --height 40% --reverse --exact --ansi\
        --header="If a worktree doesn't exist, git will create it for you." \
        --bind=enter:replace-query+print-query | awk '{print $1}'
    )

    [[ -z $worktree ]] && return

    # find existing worktrees once again
    available_worktrees=$(git worktree list | awk '{print $3}' | tr -d "[]")

    if grep -w "$worktree" <<< $available_worktrees 1> /dev/null; then
        switch_worktree "$worktree"
    else
        printf "%s\n" "Worktree named ${BOLD}$worktree${RESET} doesn't exist. Creating one..."
        create_worktree $worktree
    fi
}

init_worktree_menu
