#!/usr/bin/env sh

# FZF + Git interactively switch branches

choice=$(
         git for-each-ref --format='%(refname:short)' | fzf \
                --prompt="Switch Branch: " \
                --height 40% --reverse
)

if [ -n "$choice" ]; then
        git switch $choice
fi
