#!/usr/bin/env bash

# Script to get AWS session access tokens

# Dependencies
# 1. jq
# 2. AWS CLI
# 3. awk
# 4. GNU date

tmp_store="aws_token.txt"
work_profile_path="$HOME/.work_profile"

# Maximum possible duration "36 hours" (129,600 seconds)
# Read: https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html
duration="12 hours"
# convert to UNIX epoch and find appropriate expire limit
duration_seconds=$(( $(date -d "$duration" +%s) - $(date +%s) ))
AWS_REGION="us-west-1"
now=$(date "+%d %B, %Y (%r)")


_init(){
    # unexport any existing keys
    unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
}

_cleanup(){
    # remove the temp file we created for storing keys
    rm "$tmp_store"
}

_update_vscode_launch(){
    if test -f .vscode/launch.json;then
        launch_file_path=".vscode/launch.json"
        json=$(cat $launch_file_path)
        if jq ".configurations[].env += { AWS_ACCESS_KEY_ID: \"$1\", AWS_SECRET_ACCESS_KEY:\"$2\", AWS_SESSION_TOKEN: \"$3\", AWS_REGION: \"$AWS_REGION\" }" <<< "$json" > $launch_file_path; then
            printf "%s\n" "Updated VSCode Launch Config"
        else
            # rollback json in case of errors
            echo "$json" > $launch_file_path
        fi
    fi
}

_get_secrets() {
    if aws sts get-session-token --duration-seconds "$duration_seconds" > "$tmp_store"; then
        AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' < "$tmp_store")
        AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' < "$tmp_store")
        AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' < "$tmp_store")
        EXPIRE_TIME=$(date --date="$(jq -r '.Credentials.Expiration' < "$tmp_store")" "+%d %B, %Y (%r)")

        {
            echo "export AWS_ACCESS_KEY_ID=\"${AWS_ACCESS_KEY_ID}"\"
            echo "export AWS_SECRET_ACCESS_KEY=\"${AWS_SECRET_ACCESS_KEY}"\"
            echo "export AWS_SESSION_TOKEN=\"${AWS_SESSION_TOKEN}"\"
            echo "export AWS_REGION=\"${AWS_REGION}"\"

            echo "# Keys requested on $now"
            echo "# Keys valid till $EXPIRE_TIME"
        } > "$work_profile_path"

        printf "Expiring on %s\n" "$EXPIRE_TIME"
        printf "%s\n" "Exported as environment variables in $work_profile_path"

        _update_vscode_launch "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}" "${AWS_SESSION_TOKEN}"
    fi
}

_init
printf "%s\n" "Getting AWS Session Token"
_get_secrets
_cleanup
