#!/usr/bin/env sh

# Script to get AWS session access tokens

# Dependencies
# 1. jq
# 2. aws cli

# Maximum possible duration "36:00:00" (129,600 seconds)
# Read: https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html
duration="12:00:00"
duration_seconds=$(echo $duration | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')


_pre_script(){
    # unexport any existing keys
    unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
}

_post_script(){
    rm "aws_token.txt"
}

_pre_script

printf "%s\n" "Getting AWS Session Token"

if aws sts get-session-token --duration-seconds "$duration_seconds" > aws_token.txt; then
    AWS_ACCESS_KEY_ID=$(jq -r '.Credentials | {AccessKeyId} | join("")' < aws_token.txt)
    AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials | {SecretAccessKey} | join("")' < aws_token.txt)
    AWS_SESSION_TOKEN=$(jq -r '.Credentials | {SessionToken} | join("")' < aws_token.txt)
    EXPIRE_TIME=$(date --date="$(jq -r '.Credentials | {Expiration} | join("")' < aws_token.txt)" "+%d %B, %Y (%r)")

    echo "export AWS_ACCESS_KEY_ID=\"${AWS_ACCESS_KEY_ID}"\"> ~/.work_profile
    echo "export AWS_SECRET_ACCESS_KEY=\"${AWS_SECRET_ACCESS_KEY}"\">> ~/.work_profile
    echo "export AWS_SESSION_TOKEN=\"${AWS_SESSION_TOKEN}"\">> ~/.work_profile
    echo 'export AWS_REGION="us-west-1"' >> ~/.work_profile

    printf "Expiring on %s\n" "$EXPIRE_TIME"
    printf "%s\n" "Exported as environment variables in ~/.work_profile"
fi

_post_script
