#!/usr/bin/env python3

# Script to hide sensitive data from a command
# This script assume everything inside double quotes is sensitive

# TODO: add help & about option

from sys import stdin
from os import isatty
import re

quotes_regex = re.compile('"(.*?)"')

def hide_secrets(data: str):
    sensitive_data = re.findall(quotes_regex, data)

    for secret in sensitive_data:
        data = data.replace(secret, "*" * len(secret))
    print(data)


if __name__ == "__main__":
    is_pipe = not isatty(stdin.fileno())

    if is_pipe:
        query = stdin.read()
        hide_secrets(query)