#!/usr/bin/env python3

# Find all gists of a github user

# Usage
# Fetch only public gists
# ./gists -u Bhupesh-V
# Fetch all gists (including private)
# ./gists -au Bhupesh-V


import urllib.parse
import urllib.request
import json
import argparse
from pathlib import Path

HEADERS = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "application/vnd.github.v3+json",
    "Content-Type": "application/json",
}

BASE_URL = "https://api.github.com"


def parse_link_header(link_header):
    header_links = link_header.split(",")[0].split(";")
    if header_links[1] == ' rel="next"':
        next_page = header_links[0]
        next_page = next_page[1 : len(next_page) - 1]
    else:
        next_page = None

    return next_page


def make_request(url):
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req) as response:
        res = json.loads(response.read().decode("utf-8"))
        if response.headers["link"] is not None:
            next_url = parse_link_header(response.headers["link"])
        else:
            next_url = None

    return res, next_url


def request(url):
    res_list = []
    while True:
        res, next_url = make_request(url)
        res_list += res
        if next_url is None:
            break
        url = next_url

    return res_list


def find_all_gists(user, show_all):
    try:
        gists = request(f"{BASE_URL}/users/{user}/gists?per_page=100")
        if show_all:
            filtered_gists = gists
        else:
            filtered_gists = [gist for gist in gists if gist["public"]]

    except urllib.error.HTTPError as e:
        if e.code == 403:
            print("GitHub API rate limit exceeded. Only 60 requests/hour")
            exit()
        elif e.code == 404:
            print("User doesn't exist. Please verify username")
            exit()
        else:
            return None
    return filtered_gists


def show_gists(gists):
    """
    Output all gists in following format
    first filename or gist description, <gist url>
    """
    for gist in gists:
        if gist["description"] == "":
            first_filename = list(gist["files"].keys())
            print(f"{first_filename[0]},", end="")
        else:
            print(f"{gist['description']},", end="")
        print(f"{gist['html_url']}")


def read_token():
    """
    Read GitHub token either from .git-credentials or .env.json
    .git-credentials = https://username:TOKEN@github.com
    .env.json = {"GITHUB_TOKEN":"TOKEN"}
    """
    env_path = Path.home() / ".env.json"
    credentials_file = Path.home() / ".git-credentials"
    if env_path.is_file():
        secrets = json.loads(env_path.read_text())
        if "GITHUB_TOKEN" in secrets:
            HEADERS["Authorization"] = f"token {secrets['GITHUB_TOKEN']}"
        else:
            print("GITHUB_TOKEN not found in .env.json")
            exit()
    elif credentials_file.is_file():
        token_string = Path(credentials_file).read_text()
        # or use regex
        # token = re.search('[^https://].*:(.*)@', token_string).group(1)
        token = token_string.split(":")[2].split("@")[0]
        if token is None or token == "":
            print(
                "Error reading token from .git-credentials. Please check if the file has valid content"
            )
            exit()
        HEADERS["Authorization"] = f"token {token}"
    else:
        print("No .env.json or .git-credentials file found in home directory")
        exit()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="List GitHub gists")
    parser.epilog = """Help/Bug Report: varshneybhupesh@gmail.com"""
    parser.add_argument("-u", "--user", type=str, help="Github Username", required=True)
    parser.add_argument(
        "-a",
        "--all",
        action="store_true",
        default=False,
        help="Fetch all gists",
    )
    args = parser.parse_args()

    read_token()
    gists = find_all_gists(args.user, args.all)
    show_gists(gists)
    # print(json.dumps(gists, indent = 4))
