#!/usr/bin/env python3

# File Backup as Gist
# Script to backup files as a GitHub Gist with 0 dependency

# Usage:
# 1. Make sure you have a Personal Access Token with Gist Scope
# 2. Create a file named .env.json in your home directory with contents:
# {"GITHUB_TOKEN": "<your-token>" }
# 3. Run script: ./bkp <file-to-backup>

import urllib.request
import json, sys, os
import argparse
from datetime import datetime
from pathlib import Path

HEADERS = {
    "Accept": "application/vnd.github.v3+json",
    "Content-Type": "application/json",
}
base_url = "https://api.github.com"

# By default upload gist as a Secret
content = {
    "description": "",
    "public": False,
    # "files": {"test": {"content": "# title"}},
}


def request(url, data=None, method=None):
    if method == "PATCH":
        req = urllib.request.Request(url, data=data, headers=HEADERS)
        req.get_method = lambda: "PATCH"
    elif method == "DELETE":
        req = urllib.request.Request(url, headers=HEADERS)
        req.get_method = lambda: "DELETE"
    elif method == "POST":
        req = urllib.request.Request(url, data=data, headers=HEADERS)
    else:
        req = urllib.request.Request(url, headers=HEADERS)
    try:
        with urllib.request.urlopen(req) as response:
            res = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as e:
        print(e.reason)
        exit()
    return res, response.code


def get_backup(filename):
    # Get Gist id if we already have a backup
    print("📦 Checking for backup ...")
    res, _ = request(url=f"{base_url}/gists")
    for gist in res:
        if filename in gist["files"]:
            updated_date = datetime.strptime(
                gist["updated_at"], "%Y-%m-%dT%H:%M:%SZ"
            ).strftime("%d %b %Y")
            print(f"""✔️  Found File backup ({updated_date})""")
            gid = gist["id"]
            break
        gid = None
    return gid


def read_token():
    env_path = Path.home() / ".env.json"
    if env_path.is_file():
        secrets = json.loads(env_path.read_text())
        if "GITHUB_TOKEN" in secrets:
            HEADERS["Authorization"] = f"token {secrets['GITHUB_TOKEN']}"
        else:
            print("GITHUB_TOKEN not found in .env.json")
            exit()
    else:
        print("No .env.json file found in home directory")
        exit()


def delete_gist(filepath):
    userfile = Path(filepath)
    gist_id = get_backup(userfile.name)

    print("🚮️ Purging Gist ...")
    res, code = request(f"{base_url}/gists/{gist_id}", method="DELETE")

    print(res, code)
    if code == 204:
        print("Backup Successfully Deleted")


def controller(filepath):
    userfile = Path(filepath)
    content["files"] = {userfile.name: {"content": userfile.read_text()}}
    gist_id = get_backup(userfile.name)

    if gist_id is not None:
        print("📤 Updating ...")
        res, code = request(
            f"{base_url}/gists/{gist_id}", json.dumps(content).encode("utf-8"), "PATCH"
        )
    else:
        print(f"No backup found for file: {os.path.basename(filepath)}")
        print("Creating Backup ...")
        res, code = request(
            f"{base_url}/gists", json.dumps(content).encode("utf-8"), "POST"
        )
    if code == 200 or code == 201:
        print("Success! 😃")

    return res


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Backup text files as a GitHub Gist")
    parser.add_argument("filepath", type=str, help="Absolute file path")
    parser.add_argument(
        "-s",
        "--show-url",
        action="store_true",
        default=False,
        help="Show github gist url",
    )
    parser.add_argument(
        "-d",
        "--delete",
        action="store_true",
        default=False,
        help="Delete Gist",
    )
    args = parser.parse_args()

    read_token()

    if args.delete:
        delete_gist(args.filepath)
    else:
        data = controller(args.filepath)

    if args.show_url:
        print(f"""Gist url: {data["html_url"]}""")
