#!/usr/bin/env sh

header="Select a branch to switch to"

choice=$(git for-each-ref --format='%(refname:short)' refs/heads/* | fzf \
  --prompt="Switch branch: " \
  --height 40% --reverse
)

git switch $choice

