#!/usr/bin/env sh

# FZF + Git interactively switch branches
choice=$(git for-each-ref --format='%(refname:short)' refs/heads/* | fzf \
  --prompt="Switch branch: " \
  --height 40% --reverse \
  --header="Select a branch to switch to"
)

git switch $choice
