#!/usr/bin/env bash

selection=$(rofi -i -width 1000 -dmenu -p "Choose Snippet: " 2> /dev/null $@ < $HOME/Documents/.Varshney/snippets/links.txt)
echo -n "$selection" | xclip -selection clipboard
sleep 0.1
xclip -o -sel clip
