#!/usr/bin/env bash

# This script helps ignore unnecessary dir paths while using find

EXCLUDE_DIRS=(
    ! -path /*.git/*
    ! -path /*go/*
    "! -path /*.bundle/*"
    "! -path /*.cache/*"
    "! -path /*.local/*"
    "! -path /*.themes/*"
    "! -path /*.config/*"
    "! -path /*.codeintel/*"
    "! -path /*.mozilla/*"
    "! -path /*python2.7/*"
    "! -path /*python3.6/*"
    "! -path /*__pycache__/*"
    "! -path /*.vscode/*"
    "! -path /*.themes/*"
    "! -path /*.icons/*"
)
# additionally ignore snap/ cuz its getting expanded
find $HOME ${EXCLUDE_DIRS[@]} ! -path "/*snap/*"
